### ISSUE TITLE
genre missing in all 2018 movies and some 2017

### ISSUE THREAD

**Issue by Daniel-Plaikner** [sidooms/MovieTweetings#4]
Hello, 
I really like your MovieTweetings dataset because it’s up to date and contains only valuable information. 
However, I have one complaint and that is, that the database would be a lot more usable if all the data is complete. (I noticed that on all the 2018 and some 2017 movies the genre field is empty/missing.)
Hope you can fix that :D 

Thanks for your work and have a nice weekend.

**Comment by sidooms** [comment]
Whoops, you're right. I hadn't noticed, but it looks like the genre info has been broken for a while now. The reason was that the [OMDB API](http://www.omdbapi.com/), which is used to fetch the info, started requiring authentication. I've fixed it, and the genres should be backfilled in the next couple of days now. Thanks for the headsup!
