### ISSUE TITLE
Ratings in range from 0 to 10

### ISSUE THREAD

**Issue by janmotl** [sidooms/MovieTweetings#5]
Hi, I noticed that the ratings in  `latest/ratings.dat` contain ratings are from 0 to 10 while the article at crowdrec2013.noahlab.com.hk/papers/crowdrec2013_Dooms.pdf suggests that the ratings should be from 1 to 10. The histogram of the ratings also suggests that the lower bound should/could be 1.

What is the meaning of zeros? Is it a valid rating or some error?

**Comment by sidooms** [comment]
You're right, the dataset does include ratings ranging from 0 to 10 (bounds included), even though IMDb only allows ratings in the interval from 1 to 10. The reason that 0 is included, is because people can still change the tweet after it is formatted by the IMDb app. Basically they can insert whatever rating they want, which you can easily test for yourself by e.g., doing [a Twitter search for 'I rated imdb 100/10'](https://twitter.com/search?q=I%20rated%20imdb%20100%2F10&src=typd).

The script collecting the dataset cleans up the tweets a bit and removes all ratings lower than 0 and higher than 10. That leaves the 'artificial' value of 0 included in the dataset though. I've always considered the zeros as valid ratings since they originate from users who were pretty motivated to get their opinion out :)

**Comment by janmotl** [comment]
Thank you for your prompt reply!
